version: "3"

services:
  mmdet:
    build: ./docker
    container_name: ka
    restart: always
    working_dir: /feedback
    volumes:
      - ./:/feedback
    tty: true
    shm_size: 30gb
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

